endif

new-unode:
	@echo ""
	@echo "Please fill out the Questions"
	@echo ""
	@echo ".------------------- ------ -- ---         -"
	@echo "| How to :"
	@echo "|"
	@echo "| wrapper_name:"
	@echo "|   The wrapper name should include the version name following"
	@echo "|   pep8 convention. ie should be importable as a python module"
	@echo "|"
	@echo "| tool:"
	@echo "|   as a top level folder to group different versions of the same tool"
	@echo "|"
	@echo "| version:"
	@echo "|   Any string"
	@echo "|"
	@echo "| release data:"
	@echo "|   Any string"
	@echo "|"
	@echo "| translation_style:"
	@echo "|   Tools will mostly keep their parameters over different versions."
	@echo "|   The translation style is in the format of {tool}_style_{X}"
	@echo "|"
	@echo "| exe_<platform>:"
	@echo "|   and the executable name should be defined here"
	@echo "|"
	@echo "|"
	@echo "| Note:"
	@echo "|   - Files will be overwritten if already exist"
	@echo "|"
	@echo "+------------------ ---- --    -"
	@echo ""

	@echo "Running Unittests using pytest"

zip-exes:
	@echo "Creating new zip files and calculating md5s for new exes"
	@echo "----[to be implemented ]----"
