[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[project]
name = "urgap"
readme = "README.rst"
dynamic = ["version"]
requires-python = ">=3.10,<3.12"
urls = { Source = "https://mygithub.gsk.com/gsk-tech/urgap" }
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: Education',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: POSIX :: SunOS/Solaris',
    'Operating System :: Unix',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Chemistry',
]
dependencies = [
    'apache-libcloud==3.8.0',
    'click==8.1.8',
    'fastapi==0.118.0',
    'fastexcel==0.16.0',
    'flask==3.1.2',
    'flask-wtf==1.2.2',
    'Jinja2==3.1.6',
    'jsonschema==4.25.1',
    'nbformat>=4.2.0',
    'networkx==3.4.2',
    'openpyxl',
    'packaging==25.0',
    'pandas>=1.4.2,<2.4.0',
    'plotly',
    'polars>=1.33.0',
    'requests>=2.26,<2.33',
    'sqlalchemy==2.0.43',
    'tqdm==4.67.1',
    'uvicorn==0.37.0',
    'PyGithub==2.8.1',
    'mcp==1.16.0',
    'xlsxwriter==3.2.9'
]

[project.optional-dependencies]
# E.g. pip install "urgap[cloud]"
cloud = [
    'apache_beam==2.68.0',
    'azure-identity==1.25.1',
    'azure-keyvault-secrets==4.10.0',
    'azure-monitor-opentelemetry==1.8.1',
    'azure-storage-blob==12.26.0',
    'azure-storage-file-datalake==12.21.0',
    'azure-storage-file-share==12.22.0',
    'cloud-sql-python-connector~=1.0',
    'google-apitools==0.5.35',
    'google-cloud-logging==3.12.1',
    'google-cloud-secret-manager==2.24.0',
    'google-cloud-storage==3.4.0',
    'google-crc32c==1.7.1',
    'opentelemetry-exporter-otlp-proto-grpc==1.37.0',
    'opentelemetry-sdk==1.37.0',
    'pg8000~=1.29',
    'prefect==3.4.22',
    'prefect-kubernetes==0.6.5',
    'pysmb==1.2.13',
    'pyvis==0.3.2',
    'mcp==1.16.0',
]
databases = [
    'pymongo>=3.8.0,<5.0.0',
    'psycopg2-binary'
]
docs = [
    'sphinx',
    'sphinx-rtd-theme',
]
dev = [
    'pytest>=7.0.0',
    'pytest-asyncio>=0.21.0',
    'black>=23.0.0',
    'ruff>=0.1.0',
]
legacy = [
    'unimod-mapper~=0.6.4',
    'uparma~=1.0.1',
    'chemical-composition~=1.0.6',
    'FlowKit',
]

all = [
    'apache_beam==2.68.0',
    'azure-identity==1.25.1',
    'azure-keyvault-secrets==4.10.0',
    'azure-monitor-opentelemetry==1.8.1',
    'azure-storage-blob==12.26.0',
    'azure-storage-file-datalake==12.21.0',
    'azure-storage-file-share==12.22.0',
    'cloud-sql-python-connector~=1.0',
    'google-apitools==0.5.35',
    'google-cloud-logging==3.12.1',
    'google-cloud-secret-manager==2.24.0',
    'google-cloud-storage==3.4.0',
    'google-crc32c==1.7.1',
    'opentelemetry-exporter-otlp-proto-grpc==1.37.0',
    'opentelemetry-sdk==1.37.0',
    'pg8000~=1.29',
    'prefect-kubernetes==0.6.5',
    'prefect==3.4.22',
    'psycopg2-binary',
    'pymongo>=3.8.0,<5.0.0',
    'pysmb==1.2.13',
    'pyvis==0.3.2',
    'mcp==1.16.0',
]

[project.scripts]
uctl = "urgap.uctl.uctl:cli"

[tool.setuptools.packages.find]

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"*" = ["*.txt"]
"urgap.config_defaults" = ["*.json"]
'urgap.uctl.server.static.css' = ["*.css"]
"urgap.uctl.server.static.js" = ["*.js"]
"urgap.uctl.server.templates" = ["*.html"]
"urgap.ureport.templates" = ["*.html"]

[tool.hatch.version]
source = "versioningit"

[tool.versioningit]
default-version = "0.0.0+unknown"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
dirty = "{next_version}.dev{distance}"
distance-dirty = "{next_version}.dev{distance}"

[tool.ruff]
target-version = "py312"
line-length = 88
indent-width = 4
exclude = [
    ".git",
    "build",
    "dist",
    "docs"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "S", # Flake8 Bandit
    "E501", # Line too long
    "PLR2004", # Magic value comparison
    "RUF012", # Mutable class default
    "LOG015", # Root logger call
    "FBT001", # Boolean type hint positional argument
    "FBT002", # Boolean default value positional argument,
    "PYI034", # Wait until we drop 3.10 so Self is in typing
    "PLR0913", # Too many arguments -> TODO
    "TC003", # Causes false positives
    "D203", # Incompatible with D211
    "D213", # Incompatible with D212
    "D413", # For looks a bit more like google/numpy/pep257 style,
    "PLC0415", # Avoid unnecessary imports,
    "UP047", # Only available 3.13+
    "N801", # we do that anyway ..
    "PTH", # Ignore pathlib issues
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
force-single-line = false
known-first-party = ["urgap"]
combine-as-imports = true
lines-between-types = 1

