resources:
  repositories:
    - repository: templates
      type: github
      name: gsk-tech/dso_azure_pipeline_templates
      ref: main
      endpoint: DSO-R1-Github
  pipelines:
    - pipeline: urgapMain
      source: gsk-tech.urgap
      trigger:
        branches:
          include:
            - main
            - dev
            - refs/tags/*
trigger: none
pr:
  branches:
    exclude:
      - '*'
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    condition: succeeded()
    displayName: Build and Push
    jobs:
      - job: BuildAndPushJob
        displayName: Build And Push
        steps:
          - template: build/acr_build_and_push.yaml@templates
            parameters:
              azureSubscription: 'ARM-RD-dso-AppResources-prod'
              acrName: 'dsoazcr'
              repositoryName: 'urgap'
              dockerfilePath: 'Dockerfile-Prefect'
              buildContext: '.'