trigger:
  branches:
    include:
      - main
      - dev
      - feature/*
      - fix/*
  tags:
    include:
      - v*
pr:
  drafts: false
  branches:
    include:
      - main
      - dev
      - feature/*
      - fix/*
resources:
  repositories:
    - repository: templates
      type: github
      name: gsk-tech/dso_azure_pipeline_templates
      ref: main
      endpoint: DSO-R1-Github
variables:
  DEFAULT_PYTHON: '3.12'
pool:
  vmImage: ubuntu-latest
stages:
  - stage: CodeQuality
    displayName: 'Code Quality Checks'
    jobs:
      - job: Ruff
        displayName: 'Run Ruff'
        steps:
          - template: code_quality/ruff.yaml@templates
            parameters:
              SOURCE_FOLDER: "."
              PYTHON_VERSION: ${{ variables.DEFAULT_PYTHON }}
              RUFF_ARGS: "--exclude urgap/wrappers,urgap/ext,urgap/uftypes.py,tests,docs"
      - job: Yamllint
        displayName: 'YAML Formatter Check'
        steps:
          - template: code_quality/yamlfmt.yaml@templates
            parameters:
              SOURCE_FOLDER: "."
      - job: PrettierCheck
        displayName: Prettier JSON Check
        steps:
          - template: code_quality/prettier.yaml@templates
            parameters:
              FILE_PATTERN: "**/*.json"
      - job: YmlORYaml
        displayName: Disallow .yml Files
        steps:
          - template: code_quality/yml_check.yaml@templates
  - stage: Tests
    displayName: 'Run Unit and Integration Tests'
    dependsOn: CodeQuality
    jobs:
      - job: Tests
        displayName: 'Tests across Python versions'
        strategy:
          matrix:
            Python3.10:
              pythonVersion: '3.10'
            Python3.11:
              pythonVersion: '3.11'
            Python3.12:
              pythonVersion: '3.12'
            Python3.13:
              pythonVersion: '3.13'
        steps:
          - template: setup_urgap_test_suite.yaml
          - template: tests/setup_tests.yaml@templates
          - template: tests/tests.yaml@templates
            parameters:
              package: urgap
              testFolder: tests/unittests
              testCategory: Unittests
              envUrgapHome: $(Pipeline.Workspace)/.urgap
          - template: tests/tests.yaml@templates
            parameters:
              package: urgap
              testFolder: tests/integrationtests
              testCategory: Integrationtests
              envUrgapHome: $(Pipeline.Workspace)/.urgap
          - template: tests/coverage_report.yaml@templates
            parameters:
              sonarqubePythonVersion: ${{ variables.DEFAULT_PYTHON }}
              coverageType: 'xml'
              flags: -o ../urgap/coverage.xml
          - template: code_quality/sonarqube.yaml@templates
            parameters:
              SonarQube: dso-sonarqube-urgap
              cliProjectKey: dso-urgap
              sonarqubePythonVersion: ${{ variables.DEFAULT_PYTHON }}
              projectBaseDir: ../urgap
              sonarSources: ../urgap
              sonarExclusions: '**/tests/**,**/build/**,**/docs/**,**/utils/**,**/examples/**,**/ext/**,**/wrappers/**,**/urgap/resources/**,**/unodes/**'