trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - v*
pr: none
resources:
  repositories:
    - repository: containerhub
      type: github
      name: gsk-tech/dso-container-hub
      ref: main
      endpoint: DSO-R1-Github
pool:
  vmImage: ubuntu-latest
stages:
  - stage: SetVariables
    jobs:
      - job: Get_Urgap_Version
        steps:
          - script: |
              PACKAGE_VERSION=$(python -m setuptools_scm | sed "s/\.dev0//")
              echo "##vso[task.setvariable variable=PACKAGE_VERSION;isOutput=true]$PACKAGE_VERSION"
            displayName: Set variable PACKAGE_VERSION
  - stage: PythonPackage
    variables:
      PACKAGE_VERSION: $[stageDependencies.create_variables_stage.create_variables_job.outputs['ADO_variables.PACKAGE_VERSION']]
      REPOSITORY_NAME: gsk-tech/urgap
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    dependsOn:
      - SetVariables
    jobs:
      - job: BuildPackage
        displayName: 'Build Package'
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - script: |
              git fetch --all --tags
              git switch $(basename $(Build.SourceBranch))
              git log | head -n 5
          - script: |
              pip install urgap["all"]
              pip install build twine wheel
              python -m build
          - task: PublishBuildArtifacts@1
            displayName: 'Publish package'
            inputs:
              pathToPublish: './dist/'
              artifactName: 'package'
      - job: UploadWheel
        dependsOn: BuildPackage
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        displayName: Upload Wheel
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              artifactName: 'package'
              downloadPath: './dist/'
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: DSO-R1-Github
              repositoryName: $(REPOSITORY_NAME)
              action: edit
              target: $(Build.SourceVersion)
              tag: $(Build.SourceBranchName)
              assets: ./dist/package/*.whl
              assetUploadMode: replace
      - job: PushVersion
        dependsOn: UploadWheel
        displayName: 'Push Version to Containerhub'
        steps:
          - checkout: containerhub
            path: containerhub
            clean: true
            fetchDepth: 0
            persistCredentials: true
          - script: |-
              cd $(Pipeline.Workspace)/containerhub
              git config --global user.email "bot@dso.com"
              git config --global user.name "DSO Bot"
              git checkout -b feature/new_urgap_version_$(Build.SourceBranchName)
              git commit --allow-empty -m "new urgap version $(Build.SourceBranchName)"
              git push --set-upstream origin feature/new_urgap_version_$(Build.SourceBranchName)