import types

transcriptomics = types.SimpleNamespace()
transcriptomics.FASTA = ".transcriptomics.fa"
transcriptomics.reads = types.SimpleNamespace()
transcriptomics.reads.ANY = "transcriptomics.reads.ANY"
transcriptomics.reads.FASTQ_GZ = ".transcriptomics_fastq.gz"
transcriptomics.reads.SAM = ".transcriptomics.sam"
transcriptomics.reads.BAM = ".transcriptomics.bam"
transcriptomics.BAM_INDEX = ".transcriptomics.bai"
transcriptomics.GTF = ".transcriptomics.gtf"
transcriptomics.READS = ".transcriptomics.reads"
transcriptomics.CODON_METRICS_PLOT_HTML = ".codon_metrics.html"
transcriptomics.RIBOSOME_PROFILING_FEATHER = ".rp.feather"
transcriptomics.CUTADAPT_STATS_JSON = ".cutadapt.json"
transcriptomics.STAR_2_INDEX = ".star2.idx"
transcriptomics.STAR_2_INDEX_META_ZIP = ".star2_idx_meta.zip"
transcriptomics.STAR_2_QUANT_TSV = ".star2_quant.tsv"
transcriptomics.BOWTIE_1_ALIGNMENT = ".bowtie1.align"
transcriptomics.BOWTIE_1_INDEX = ".bowtie1.idx"
transcriptomics.BOWTIE_1_INDEX_MAPPING = ".bowtie_1_index_mapping.json"
transcriptomics.KALLISTO_INDEX = ".kallisto.idx"
transcriptomics.KALLISTO_QUANT_TSV = ".kallisto_quant.tsv"
transcriptomics.FASTQC_HTML = ".fastqc.html"
transcriptomics.FASTQC_ZIP = ".fastqc.zip"
transcriptomics.cellranger = types.SimpleNamespace()
transcriptomics.cellranger.SAMPLE_SHEET = ".cellranger_sample_sheet.csv"
transcriptomics.cellranger.NOVASEQ_INPUT_TAR = ".cellranger_novaseq_input.tar"
transcriptomics.cellranger.MKFASTQ_OUTPUT_TAR = ".cellranger_mkfastq_output.tar"
transcriptomics.cellranger.REFERENCE_VDJ = ".10xreference_vdj.tar"
transcriptomics.cellranger.REFERENCE_GENOME = ".10xreference_genome.tar"
transcriptomics.cellranger.FEATUREREF_MULTI_CSV = ".cellranger_featureref_multi.csv"
transcriptomics.cellranger.MULTI_OUTPUT_TAR = ".cellranger_multi_output.tar"
transcriptomics.cellranger.FILTERED_OUTPUT_TAR = ".cellranger_filtered_output.tar"
transcriptomics.cellranger.SCRIPT = ".SCRIPT.sh"

