name: Push to Pypi
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Upload to PyPi
        uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PROD_PYPI }}
          requirements: twine build
          pip: build
          upload: true
