# t
# For reference: https://github.com/JamesIves/github-pages-deploy-action
name: Deploy Sphinx docu to Pages.
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-and-deploy:
    #    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build HTML
        run: |
          pip install --upgrade pip
          pip install ./"[docs, cloud]"
          make sphinx-html
      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html # The folder the action should deploy.